language: c

os:
  - linux
  - osx

env:
  matrix:
    - CONDA_PY=26 CONDA_NPY=16
    - CONDA_PY=27 CONDA_NPY=16
    - CONDA_PY=26 CONDA_NPY=17
    - CONDA_PY=27 CONDA_NPY=17
    - CONDA_PY=33 CONDA_NPY=17
    - CONDA_PY=26 CONDA_NPY=18
    - CONDA_PY=27 CONDA_NPY=18
    - CONDA_PY=33 CONDA_NPY=18
    - CONDA_PY=34 CONDA_NPY=18
    - CONDA_PY=26 CONDA_NPY=19
    - CONDA_PY=27 CONDA_NPY=19
    - CONDA_PY=33 CONDA_NPY=19
    - CONDA_PY=34 CONDA_NPY=19

  global:
    - secure: "C/53r3QGcEslm6rPT4/+IKxLVcXW/mgBIVyQ1eLCaFP4N4TqxFatfuiBQGP1TJI1uLDFVgaKjaDozJDYZcD0pq1fLqySZpHZa8m2eL/04+TH0HUtBtym+/e+QilqyxaRhvQNKcUDnjnRwSaLsLO0ol+a6+MjL6relDSIVDQmP3s="

install:
  - source continuous-integration/travis/install_$TRAVIS_OS_NAME.sh

script:
  - conda build astropy-0.3.x --quiet
  - conda build astropy-0.4.x --quiet
  - conda build astropy-1.0.x --quiet

after_success:
  - python continuous-integration/move-conda-package.py astropy-0.3.x
  - python continuous-integration/move-conda-package.py astropy-0.4.x
  - python continuous-integration/move-conda-package.py astropy-1.0.x
  - binstar -t $BINSTAR_TOKEN upload --force *.tar.bz2
