package:
  name: astropy
  version: !!str 1.0rc2

source:
  fn: astropy-1.0rc2.tar.gz
  url: http://pypi.python.org/packages/source/a/astropy/astropy-1.0rc2.tar.gz
  md5: 5c3a9f7a4a6951264357988cebabafd9

requirements:
  build:
    - python
    - setuptools
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - astropy
  commands:
    - python -c "import astropy; astropy.test()"

about:
  home: http://www.astropy.org
  license: BSD
