package:
  name: astropy
  version: !!str 1.0

source:
  fn: astropy-1.0.tar.gz
  url: http://pypi.python.org/packages/source/a/astropy/astropy-1.0.tar.gz
  md5: 1f15b51eb7cbad3345a34770c87ef906

requirements:
  build:
    - python
    - setuptools
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - astropy
#  commands:
#    - python -c "import astropy; astropy.test()"

about:
  home: http://www.astropy.org
  license: BSD
