package:
  name: astropy
  version: !!str 1.0.1

source:
  fn: astropy-1.0.1.tar.gz
  url: http://pypi.python.org/packages/source/a/astropy/astropy-1.0.1.tar.gz
  md5: 89511396966f4a34919e6971ab5e4d34

requirements:
  build:
    - python
    - setuptools
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - astropy
#  commands:
#    - python -c "import astropy; astropy.test()"

about:
  home: http://www.astropy.org
  license: BSD
